### ISSUE TITLE
Add ability to change glow color

### ISSUE THREAD

**Issue by GriffinCodes** [TheTechdoodle/survival-invisiframes#2]
We currently use glowing item frames to make notes in our builds for later, and we thought it would be neat if you could change the glow color, to categorize notes. This could be done by right clicking the item frame with a dye, or crafting it with one?

![image](https://user-images.githubusercontent.com/12417961/125021479-b8586500-e048-11eb-8681-fcdfe79b0365.png)

I realize this is a bit out of scope for the plugin, but I figured I'd give it a shot :slightly_smiling_face: 

Thank you!

**Comment by techchrism** [comment]
Interesting idea but I agree, it's a bit out of scope (since the glowing is really just to indicate that it's a "special" item frame). Let me see if I can find a command or whip up a quick plugin to do the trick. It might be tricky because I think glowing color has to do with scoreboard teams or something like that.

**Comment by techchrism** [comment]
It looks like this can be done with a few simple commands for the colors you want:

 - `/team add {team name}`
 - `/team modify {team name} color {color}`
 - `/team join {team name} @e[type=minecraft:item_frame,sort=nearest,limit=1]`

Then you can create a team for each color you want and add in the frames. The third command colors the item frame closest to the player.

**Comment by GriffinCodes** [comment]
No worries :) [It was easy enough to add ourselves](https://github.com/ProjectEdenGG/Nexus/commit/66e27864e86b41e46e4caaa14ce9dda37ea587e2)
